package shunt

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const usageText = `local-shunt: delegate file reading and writing to a worker model (Ollama or an OpenAI-compatible API).

Usage:
  bulk-read --question "..." --paths FILE... [--diff [SPEC]] [--provider NAME] [--model NAME] [--max-output N]
  code-write --spec "..." [--reference FILE...] [--target PATH] [--force] [--provider NAME] [--model NAME] [--max-output N]
  local-shunt stats [--since YYYY-MM-DD] [--session ID]
  local-shunt usage [SESSION_ID | TRANSCRIPT.jsonl]... [--json]
  local-shunt bench TASKS.json [--runs N] [--task ID]... [--out FILE] [--claude PATH]
  local-shunt bench-report RESULTS.jsonl...
  local-shunt hook pre-tool-use|session-start
  local-shunt mcp
  local-shunt version

bulk-read and code-write are also available as "local-shunt bulk-read" and "local-shunt code-write".

bulk-read
  --question, -q TEXT   the specific question to answer (required)
  --paths FILE...       files to read; '-' reads standard input (paths may also be given as arguments)
  --diff [SPEC]         also read "git diff SPEC", e.g. HEAD, main...HEAD, --cached, or "HEAD -- src/"
                        (default: unstaged changes; use --diff=SPEC when SPEC starts with -)

code-write
  --spec TEXT           what to generate: signatures, test cases, conventions (required)
  --reference FILE...   files whose patterns the output should follow; pass the file generated by
                        the previous call to build on it
  --target PATH         file to write; without it the generated code goes to standard output
  --force               overwrite an existing target

Common options
  --provider NAME       ollama, openai, openai-compatible or openrouter
  --model NAME          override the configured model
  --max-output N        output token limit (bulk-read default 1024, code-write default 4096)
`

type flagKind int

const (
	flagString flagKind = iota
	flagInt
	flagBool
	flagList        // one or more values, repeatable
	flagOptionalStr // value optional
)

type flagSpec struct {
	names []string
	kind  flagKind
}

type parsedArgs struct {
	values     map[string]string
	lists      map[string][]string
	bools      map[string]bool
	set        map[string]bool
	positional []string
}

// parseArgs parses GNU-style options. Each flag is stored under its first name.
func parseArgs(args []string, specs []flagSpec) (*parsedArgs, error) {
	lookup := map[string]flagSpec{}
	for _, spec := range specs {
		for _, name := range spec.names {
			lookup[name] = spec
		}
	}
	parsed := &parsedArgs{values: map[string]string{}, lists: map[string][]string{}, bools: map[string]bool{}, set: map[string]bool{}}
	isOption := func(arg string) bool { return strings.HasPrefix(arg, "-") && arg != "-" }

	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			parsed.positional = append(parsed.positional, args[i+1:]...)
			break
		}
		if !isOption(arg) {
			parsed.positional = append(parsed.positional, arg)
			continue
		}
		name, inline, hasInline := strings.Cut(arg, "=")
		spec, ok := lookup[name]
		if !ok {
			return nil, usageError("unrecognized option %s (see --help)", name)
		}
		key := spec.names[0]
		parsed.set[key] = true
		switch spec.kind {
		case flagBool:
			if hasInline {
				return nil, usageError("option %s takes no value", name)
			}
			parsed.bools[key] = true
		case flagString, flagInt:
			value := inline
			if !hasInline {
				if i+1 >= len(args) || (isOption(args[i+1]) && spec.kind == flagString && strings.HasPrefix(args[i+1], "--")) {
					return nil, usageError("option %s needs a value", name)
				}
				i++
				value = args[i]
			}
			if spec.kind == flagInt {
				if _, err := strconv.Atoi(value); err != nil {
					return nil, usageError("option %s needs an integer, got %s", name, pyQuote(value))
				}
			}
			parsed.values[key] = value
		case flagOptionalStr:
			value := inline
			if !hasInline && i+1 < len(args) && !isOption(args[i+1]) {
				i++
				value = args[i]
			}
			parsed.values[key] = value
		case flagList:
			if hasInline {
				parsed.lists[key] = append(parsed.lists[key], inline)
				continue
			}
			start := len(parsed.lists[key])
			for i+1 < len(args) && !isOption(args[i+1]) {
				i++
				parsed.lists[key] = append(parsed.lists[key], args[i])
			}
			if len(parsed.lists[key]) == start {
				return nil, usageError("option %s needs at least one value", name)
			}
		}
	}
	return parsed, nil
}

func (p *parsedArgs) intValue(key string) int {
	n, _ := strconv.Atoi(p.values[key])
	return n
}

var modelFlags = []flagSpec{
	{[]string{"--provider"}, flagString},
	{[]string{"--model"}, flagString},
	{[]string{"--max-output"}, flagInt},
}

func checkProvider(p *parsedArgs) error {
	if provider, ok := p.values["--provider"]; ok && !contains(sortedProviderNames, provider) {
		return usageError("invalid provider %s (choose from %s)", pyQuote(provider), strings.Join(sortedProviderNames, ", "))
	}
	return nil
}

// commandAliases maps executable and command names to canonical commands.
var commandAliases = map[string]string{
	"bulk-read": "bulk-read", "read": "bulk-read",
	"code-write": "code-write", "write": "code-write",
}

// Main runs the CLI and returns the exit code.
func Main(argv []string, stdin io.Reader, stdout, stderr io.Writer) int {
	name := strings.TrimSuffix(filepath.Base(argv[0]), ".exe")
	args := argv[1:]
	command, isAlias := commandAliases[name]
	if !isAlias {
		if len(args) == 0 {
			fmt.Fprint(stderr, usageText)
			return exitUsage
		}
		command, args = args[0], args[1:]
		if canonical, ok := commandAliases[command]; ok {
			command = canonical
		}
	}
	for _, arg := range args {
		if arg == "--" {
			break
		}
		if arg == "-h" || arg == "--help" {
			fmt.Fprint(stdout, usageText)
			return 0
		}
	}

	switch command {
	case "-h", "--help", "help":
		fmt.Fprint(stdout, usageText)
		return 0
	case "version", "--version":
		fmt.Fprintln(stdout, "local-shunt "+Version)
		return 0
	case "hook":
		mode := "pre-tool-use"
		if len(args) > 0 {
			mode = args[0]
		}
		return RunHook(mode, stdin, stdout)
	case "mcp":
		return RunMCP(stdin, stdout)
	}

	savedProgress := progressOut
	progressOut = stderr
	defer func() { progressOut = savedProgress }()

	cfg := DefaultConfig()
	var (
		run      func() (string, error)
		rawWrite bool // code-write to stdout: print the content unchanged
	)
	fail := func(err error) int {
		fmt.Fprintln(stderr, "local-shunt: "+err.Error())
		return exitUsage
	}

	switch command {
	case "bulk-read":
		p, err := parseArgs(args, append([]flagSpec{
			{[]string{"--question", "-q"}, flagString},
			{[]string{"--paths", "--files"}, flagList},
			{[]string{"--diff"}, flagOptionalStr},
		}, modelFlags...))
		if err != nil {
			return fail(err)
		}
		if err := checkProvider(p); err != nil {
			return fail(err)
		}
		if !p.set["--question"] {
			return fail(usageError("--question is required"))
		}
		cfg = ApplyOverrides(LoadConfig(""), p.values["--provider"], p.values["--model"])
		files := append(p.lists["--paths"], p.positional...)
		opts := ReadOptions{Files: files, Question: p.values["--question"], MaxOutput: p.intValue("--max-output")}
		if diff, ok := p.values["--diff"]; ok {
			opts.Diff = &diff
		}
		if contains(files, "-") {
			data, err := io.ReadAll(stdin)
			if err != nil {
				return fail(usageError("cannot read standard input: %v", err))
			}
			if data == nil {
				data = []byte{}
			}
			opts.Stdin = data
		}
		run = func() (string, error) { return RunRead(cfg, opts) }

	case "code-write":
		p, err := parseArgs(args, append([]flagSpec{
			{[]string{"--spec"}, flagString},
			{[]string{"--reference", "--context"}, flagList},
			{[]string{"--target", "--out"}, flagString},
			{[]string{"--force"}, flagBool},
		}, modelFlags...))
		if err != nil {
			return fail(err)
		}
		if err := checkProvider(p); err != nil {
			return fail(err)
		}
		if !p.set["--spec"] {
			return fail(usageError("--spec is required"))
		}
		if len(p.positional) > 0 {
			return fail(usageError("unexpected argument %s; pass reference files with --reference", p.positional[0]))
		}
		cfg = ApplyOverrides(LoadConfig(""), p.values["--provider"], p.values["--model"])
		_, hasTarget := p.values["--target"]
		opts := WriteOptions{
			Out:       p.values["--target"],
			Spec:      p.values["--spec"],
			Context:   p.lists["--reference"],
			Force:     p.bools["--force"],
			MaxOutput: p.intValue("--max-output"),
			Stdout:    !hasTarget,
		}
		rawWrite = !hasTarget
		run = func() (string, error) {
			message, content, err := RunWrite(cfg, opts)
			if err != nil || !rawWrite {
				return message, err
			}
			fmt.Fprintln(stderr, message)
			return content, nil
		}

	case "stats":
		p, err := parseArgs(args, []flagSpec{{[]string{"--since"}, flagString}, {[]string{"--session"}, flagString}})
		if err != nil {
			return fail(err)
		}
		if len(p.positional) > 0 {
			return fail(usageError("unexpected argument %s", p.positional[0]))
		}
		run = func() (string, error) { return RunStats(p.values["--since"], p.values["--session"]), nil }

	case "usage":
		p, err := parseArgs(args, []flagSpec{{[]string{"--json"}, flagBool}})
		if err != nil {
			return fail(err)
		}
		run = func() (string, error) { return RunUsage(p.positional, p.bools["--json"]) }

	case "bench":
		p, err := parseArgs(args, []flagSpec{
			{[]string{"--runs"}, flagInt},
			{[]string{"--task"}, flagString},
			{[]string{"--out"}, flagString},
			{[]string{"--claude"}, flagString},
		})
		if err != nil {
			return fail(err)
		}
		// --task is repeatable; collect every occurrence.
		var only []string
		for i := 0; i < len(args); i++ {
			if args[i] == "--task" && i+1 < len(args) {
				only = append(only, args[i+1])
				i++
			} else if value, ok := strings.CutPrefix(args[i], "--task="); ok {
				only = append(only, value)
			}
		}
		if len(p.positional) != 1 {
			return fail(usageError("bench needs exactly one task file"))
		}
		runs := 3
		if p.set["--runs"] {
			runs = p.intValue("--runs")
		}
		claude := p.values["--claude"]
		if claude == "" {
			claude = "claude"
		}
		run = func() (string, error) { return RunBench(p.positional[0], runs, only, p.values["--out"], claude) }

	case "bench-report":
		p, err := parseArgs(args, nil)
		if err != nil {
			return fail(err)
		}
		if len(p.positional) == 0 {
			return fail(usageError("bench-report needs at least one results file"))
		}
		run = func() (string, error) { return RunBenchReport(p.positional) }

	default:
		fmt.Fprintf(stderr, "local-shunt: unknown command %s\n\n%s", pyQuote(command), usageText)
		return exitUsage
	}

	code, text := execute(commandEvent(command), cfg, run)
	switch {
	case code != 0:
		fmt.Fprintln(stderr, text)
	case rawWrite:
		fmt.Fprint(stdout, text)
	default:
		fmt.Fprintln(stdout, text)
	}
	return code
}

// commandEvent names a command in the log, matching the MCP server's names.
func commandEvent(command string) string {
	switch command {
	case "bulk-read":
		return "read"
	case "code-write":
		return "write"
	}
	return command
}

// Run is the process entry point.
func Run() {
	os.Exit(Main(os.Args, os.Stdin, os.Stdout, os.Stderr))
}
