package shunt

// MCP server (stdio, newline-delimited JSON-RPC 2.0).
//
// Exposes the worker as MCP tools: shunt_read, shunt_write, shunt_stats.
// Progress messages go to stderr; stdout carries protocol only.

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const latestProtocol = "2025-06-18"

func jsonUnmarshalNumber(data []byte, v any) error {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	if err := dec.Decode(v); err != nil {
		return err
	}
	if dec.More() {
		return fmt.Errorf("unexpected data after JSON value")
	}
	return nil
}

type toolProperty struct {
	Type        string   `json:"type"`
	Items       any      `json:"items,omitempty"`
	Enum        []string `json:"enum,omitempty"`
	Minimum     *int     `json:"minimum,omitempty"`
	Description string   `json:"description"`
	Default     any      `json:"default,omitempty"`
}

type toolSchema struct {
	Type                 string   `json:"type"`
	Properties           record   `json:"properties"`
	Required             []string `json:"required,omitempty"`
	AdditionalProperties bool     `json:"additionalProperties"`
	props                map[string]toolProperty
}

type tool struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	InputSchema toolSchema     `json:"inputSchema"`
	Meta        map[string]any `json:"_meta,omitempty"`
}

func schema(required []string, props ...field) toolSchema {
	s := toolSchema{Type: "object", Required: required, Properties: record(props), props: map[string]toolProperty{}}
	for _, p := range props {
		s.props[p.Key] = p.Value.(toolProperty)
	}
	return s
}

var mcpTools = func() []tool {
	one := 1
	modelProps := []field{
		{"provider", toolProperty{Type: "string", Enum: sortedProviderNames, Description: "Override the configured provider."}},
		{"model", toolProperty{Type: "string", Description: "Override the configured model."}},
		{"max_output", toolProperty{Type: "integer", Minimum: &one, Description: "Output token limit."}},
	}
	stringArray := map[string]string{"type": "string"}
	return []tool{
		{
			Name: "shunt_read",
			Description: "Answer a specific question about large text files, several files at once, or a large git diff by " +
				"delegating the reading to a worker model (local Ollama or a configured API). Returns a short answer " +
				"with line ranges and a 'Not covered or uncertain' section, instead of the whole text. Ask narrow " +
				"questions; for a follow-up, call again with the same files, which costs you only the answer. The " +
				"output is an unverified summary: spot-check key claims with Read and offset/limit, and read exact " +
				"text yourself before editing.",
			InputSchema: schema([]string{"question"}, append([]field{
				{"files", toolProperty{Type: "array", Items: stringArray, Description: "File paths. Prefer absolute paths. Pass every file the question involves."}},
				{"question", toolProperty{Type: "string", Description: "The specific question to answer from the files."}},
				{"diff", toolProperty{Type: "string", Description: "Also read `git diff <diff>` from the project, e.g. \"HEAD\" (uncommitted changes), " +
					"\"main...HEAD\", \"--cached\", or \"HEAD -- src/\". An empty string reads unstaged changes."}},
			}, modelProps...)...),
			// Load the schema up front: with tool search, a deferred tool costs Claude an extra
			// ToolSearch turn right after a blocked read.
			Meta: map[string]any{"anthropic/alwaysLoad": true},
		},
		{
			Name: "shunt_write",
			Description: "Generate one new boilerplate file (test scaffolding, fixtures, type definitions, repetitive code " +
				"following an example) with the worker model and write it to disk. Returns only the path and line " +
				"count. Refuses to overwrite unless force is true. Not for business logic, concurrency or " +
				"security-sensitive code. Run tests or a linter on the result.",
			InputSchema: schema([]string{"out", "spec"}, append([]field{
				{"out", toolProperty{Type: "string", Description: "Output file path. Prefer an absolute path."}},
				{"spec", toolProperty{Type: "string", Description: "What to generate: signatures, test cases, conventions."}},
				{"context", toolProperty{Type: "array", Items: stringArray, Description: "Files to imitate or test. Always pass at least one existing file whose patterns the output " +
					"should follow; for a follow-up, pass the file generated by the previous call."}},
				{"force", toolProperty{Type: "boolean", Description: "Overwrite an existing file.", Default: false}},
			}, modelProps...)...),
		},
		{
			Name:        "shunt_stats",
			Description: "Summarize local-shunt usage: hook decisions, delegated reads and writes, estimated token savings.",
			InputSchema: schema(nil,
				field{"since", toolProperty{Type: "string", Description: "Only records on or after this date (YYYY-MM-DD)."}},
				field{"session", toolProperty{Type: "string", Description: "Only records from this Claude session ID."}},
			),
		},
	}
}()

func findTool(name string) *tool {
	for i := range mcpTools {
		if mcpTools[i].Name == name {
			return &mcpTools[i]
		}
	}
	return nil
}

// coerceToolArgs repairs common client mistakes: arrays sent as JSON strings or a single
// path, numbers and booleans sent as strings.
func coerceToolArgs(t *tool, args map[string]any) map[string]any {
	fixed := make(map[string]any, len(args))
	for key, value := range args {
		fixed[key] = value
		s, isString := value.(string)
		if !isString {
			continue
		}
		switch t.InputSchema.props[key].Type {
		case "array":
			var decoded any
			if json.Unmarshal([]byte(s), &decoded) == nil {
				if list, ok := decoded.([]any); ok {
					fixed[key] = list
					continue
				}
			}
			fixed[key] = []any{s}
		case "integer":
			if trimmed := strings.TrimSpace(s); isDigits(trimmed) {
				fixed[key] = json.Number(trimmed)
			}
		case "boolean":
			if lower := strings.ToLower(s); lower == "true" || lower == "false" {
				fixed[key] = lower == "true"
			}
		}
	}
	return fixed
}

func checkToolArgs(t *tool, args map[string]any) error {
	props := t.InputSchema.props
	var unknown []string
	for key := range args {
		if _, ok := props[key]; !ok {
			unknown = append(unknown, key)
		}
	}
	if len(unknown) > 0 {
		sort.Strings(unknown)
		return fmt.Errorf("unknown argument(s): %s", strings.Join(unknown, ", "))
	}
	for _, key := range t.InputSchema.Required {
		if _, ok := args[key]; !ok {
			return fmt.Errorf("missing required argument: %s", key)
		}
	}
	for _, key := range sortedKeys(args) {
		value, prop := args[key], props[key]
		ok := false
		switch prop.Type {
		case "string":
			var s string
			s, ok = value.(string)
			if ok && len(prop.Enum) > 0 {
				ok = contains(prop.Enum, s)
			}
		case "integer":
			if n, isNumber := value.(json.Number); isNumber {
				_, err := strconv.ParseInt(n.String(), 10, 64)
				ok = err == nil
			}
		case "boolean":
			_, ok = value.(bool)
		case "array":
			var list []any
			if list, ok = value.([]any); ok {
				for _, item := range list {
					if _, isString := item.(string); !isString {
						ok = false
					}
				}
			}
		}
		if !ok {
			return fmt.Errorf("argument %s must be a valid %s", key, prop.Type)
		}
	}
	return nil
}

func stringList(value any) []string {
	list, _ := value.([]any)
	out := make([]string, 0, len(list))
	for _, item := range list {
		out = append(out, asString(item))
	}
	return out
}

func intArg(value any) int {
	if n, ok := value.(json.Number); ok {
		i, _ := strconv.Atoi(n.String())
		return i
	}
	return 0
}

func toolResult(text string, isError bool) map[string]any {
	return map[string]any{"content": []map[string]string{{"type": "text", "text": text}}, "isError": isError}
}

func callTool(name string, args map[string]any) map[string]any {
	t := findTool(name)
	args = coerceToolArgs(t, args)
	if err := checkToolArgs(t, args); err != nil {
		return toolResult("local-shunt: "+err.Error(), true)
	}

	cfg := ApplyOverrides(LoadConfig(""), asString(args["provider"]), asString(args["model"]))
	var (
		command string
		run     func() (string, error)
	)
	switch name {
	case "shunt_read":
		opts := ReadOptions{Files: stringList(args["files"]), Question: asString(args["question"]), MaxOutput: intArg(args["max_output"])}
		if diff, ok := args["diff"].(string); ok {
			opts.Diff = &diff
		}
		command, run = "read", func() (string, error) { return RunRead(cfg, opts) }
	case "shunt_write":
		force, _ := args["force"].(bool)
		opts := WriteOptions{Out: asString(args["out"]), Spec: asString(args["spec"]), Context: stringList(args["context"]), Force: force, MaxOutput: intArg(args["max_output"])}
		command, run = "write", func() (string, error) {
			message, _, err := RunWrite(cfg, opts)
			return message, err
		}
	default:
		command, run = "stats", func() (string, error) { return RunStats(asString(args["since"]), asString(args["session"])), nil }
	}
	code, text := execute(command, cfg, run)
	return toolResult(text, code != 0)
}

func handleMessage(message map[string]any) any {
	method, hasMethod := message["method"]
	msgID, isRequest := message["id"]
	params := asMap(message["params"])
	if params == nil {
		params = map[string]any{}
	}
	result := func(value any) any {
		return record{{"jsonrpc", "2.0"}, {"id", msgID}, {"result", value}}
	}
	fail := func(code int, text string) any {
		return record{{"jsonrpc", "2.0"}, {"id", msgID}, {"error", record{{"code", code}, {"message", text}}}}
	}

	if !isRequest {
		return nil // notifications/initialized, notifications/cancelled, ...
	}
	name, isString := method.(string)
	if !hasMethod || !isString {
		return fail(-32600, "invalid request")
	}
	switch name {
	case "initialize":
		protocol, _ := params["protocolVersion"].(string)
		if protocol == "" {
			protocol = latestProtocol
		}
		return result(record{
			{"protocolVersion", protocol},
			{"capabilities", map[string]any{"tools": map[string]any{"listChanged": false}}},
			{"serverInfo", map[string]string{"name": "local-shunt", "version": Version}},
			{"instructions", "Use shunt_read instead of reading large files in full when you need specific facts from them. " +
				"Use Read with offset/limit for exact text."},
		})
	case "ping":
		return result(map[string]any{})
	case "tools/list":
		return result(map[string]any{"tools": mcpTools})
	case "tools/call":
		toolName, _ := params["name"].(string)
		if findTool(toolName) == nil {
			return fail(-32602, fmt.Sprintf("unknown tool: %s", pyStr(params["name"])))
		}
		rawArgs := params["arguments"]
		if rawArgs == nil {
			rawArgs = map[string]any{}
		}
		args, ok := rawArgs.(map[string]any)
		if !ok {
			return fail(-32602, "arguments must be an object")
		}
		return result(callTool(toolName, args))
	}
	return fail(-32601, "method not found: "+name)
}

// RunMCP serves the MCP protocol until stdin closes.
func RunMCP(stdin io.Reader, stdout io.Writer) int {
	project := os.Getenv("CODEX_PROJECT_DIR")
	if project == "" {
		project = os.Getenv("CLAUDE_PROJECT_DIR")
	}
	if project != "" {
		if stat, err := os.Stat(project); err == nil && stat.IsDir() {
			_ = os.Chdir(project) // resolve relative paths against the project
		}
	}
	reader := bufio.NewReader(stdin)
	for {
		line, readErr := reader.ReadBytes('\n')
		if trimmed := bytes.TrimSpace(line); len(trimmed) > 0 {
			response := handleLine(trimmed)
			if response != nil {
				if encoded, err := marshalJSON(response); err == nil {
					_, _ = stdout.Write(append(encoded, '\n'))
				}
			}
		}
		if readErr != nil {
			return 0
		}
	}
}

func handleLine(line []byte) (response any) {
	var decoded any
	if jsonUnmarshalNumber(line, &decoded) != nil {
		return record{{"jsonrpc", "2.0"}, {"id", nil}, {"error", record{{"code", -32700}, {"message", "parse error"}}}}
	}
	message, ok := decoded.(map[string]any)
	if !ok {
		return record{{"jsonrpc", "2.0"}, {"id", nil}, {"error", record{{"code", -32600}, {"message", "batches are not supported"}}}}
	}
	defer func() {
		if r := recover(); r != nil { // keep the server alive
			response = record{{"jsonrpc", "2.0"}, {"id", message["id"]}, {"error", record{{"code", -32603}, {"message", fmt.Sprint(r)}}}}
		}
	}()
	return handleMessage(message)
}
